# Generated by Django 3.1.3 on 2020-12-17 20:03

from django.db import migrations, models
import links.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_link', models.URLField(verbose_name='Link to redirect')),
                ('truncated_link_uuid', models.UUIDField(db_index=True, default=uuid.UUID('35f690e1-7718-488a-b9c1-3f6cc537df78'), editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Link',
                'ordering': ('-created',),
            },
            bases=(models.Model, links.models.ModelDiffMixin),
        ),
    ]
