# Generated by Django 3.1.3 on 2020-12-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='truncated_link_uuid',
            field=models.CharField(db_index=True, editable=False, max_length=10, unique=True),
        ),
    ]
